name: Post to Bluesky
on:
    push:
        branches:
            - master
        paths:
            - src/pages/blog/*.md

jobs:
    post-to-bluesky:
        name: Post to Bluesky
        runs-on: ubuntu-22.04
        steps:
            - uses: actions/checkout@v4
              with:
                fetch-depth: 5
            - name: Find any files in src/pages/blog/*.md that were touched by this commit
              run: git diff --name-only HEAD~1 -- src/pages/blog/*.md > blog-files.txt
            - name: Run each file through the script
              run: npm ci && npm run ci:bsky
              env:
                BLUESKY_IDENTIFIER: ${{ secrets.BLUESKY_IDENTIFIER }}
                BLUESKY_TOKEN: ${{ secrets.BLUESKY_TOKEN }}
