name: Deploy to Cloudflare Workers Sites

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v1

    - name: Build the PHP and garbage collect
      run: |
        cd ./public
        php ./index.php >> ./index.html
        php ./cv.php >> ./cv.html
        rm ./index.php ./cv.php ./portfolio.yml
        cd ..

    - name: Publish to Cloudflare
      uses: cloudflare/wrangler-action@1.3.0
      with:
        email: ${{ secrets.CF_EMAIL }}
        apiKey: ${{ secrets.CF_API_KEY }}
