name: Deploy to Cloudflare Workers Sites

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1

    - name: Build the PHP and garbage collect
      run: php index.php >> index.html && rm index.php portfolio.yml
